# Generated by Django 5.2.4 on 2025-07-10 13:02

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='biz_contact',
            field=models.CharField(default='', max_length=20, validators=[customers.models.validate_phone]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='biz_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='biz_mail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='biz_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
