# Generated by Django 5.2.4 on 2025-07-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='vendor',
            name='paystack_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='paystack_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
